-- Auto-generated by DMS — do not edit manually

hl.monitor({ output = "DP-1", mode = "1920x1080@144.001", position = "0x0", scale = 1, vrr = 0 })
hl.monitor({ output = "DP-2", mode = "1920x1080@60.000", position = "1920x0", scale = 1, vrr = 0 })
