splash = false
wallpaper {
	monitor = DP-2
	path = /home/nedwardo/documents/wallpapers
	fit_mode = contain
	timeout = 1800
}

wallpaper {
	monitor = DP-1
	path = /home/nedwardo/documents/wallpapers
	fit_mode = contain
	timeout = 1800
}
